name: build-lambda

on:
  workflow_call:

jobs:
  build:
    name: Build Lambda artifact
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Build Lambda
        run: |
          chmod +x scripts/build-lambda.sh
          ./scripts/build-lambda.sh hello dist/hello.zip

      - name: Upload lambda artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-zip
          path: dist/hello.zip

