name: ci

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_call:
    inputs:
      run_build:
        description: Run build job
        type: boolean
        default: true
      run_lint:
        description: Run lint job
        type: boolean
        default: true

jobs:
  build:
    name: Build Lambda artifact
    if: ${{ github.event_name != 'workflow_call' || inputs.run_build }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true
          cache-dependency-path: |
            **/go.sum

      - name: Build Lambda hello
        run: |
          chmod +x scripts/build-lambda.sh
          ./scripts/build-lambda.sh hello dist/hello.zip

      - name: Upload lambda artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-zip
          path: dist/hello.zip

  lint:
    name: Lint (golangci-lint)
    if: ${{ github.event_name != 'workflow_call' || inputs.run_lint }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true
          cache-dependency-path: |
            **/go.sum

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
