name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build Lambda artifact
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true
          cache-dependency-path: |
            **/go.sum

      - name: Build Lambda hello
        run: |
          chmod +x scripts/build-lambda.sh
          ./scripts/build-lambda.sh hello dist/hello.zip

      - name: Upload lambda artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-zip
          path: dist/hello.zip
          retention-days: 30
          compression-level: 6

  lint:
    name: Lint (${{ matrix.module }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        module: [ "infra", "lambda/hello" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true
          cache-dependency-path: |
            **/go.sum

      - name: Run golangci-lint (${{ matrix.module }})
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ${{ matrix.module }}
          args: ./...
