name: pulumi-preview

on:
  pull_request:

jobs:
  preview:
    name: Pulumi preview
    runs-on: ubuntu-latest
    environment: pr
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      actions: read
      attestations: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download lambda artifact from build workflow
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          pr: ${{ github.event.number }}
          name: lambda-zips
          path: dist/
          if_no_artifact_found: fail

      - name: Setup Go (for Pulumi program)
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true
          cache-dependency-path: infra/go.sum

      - name: Build Pulumi binary
        working-directory: infra
        run: |
          go mod tidy
          go build -o infra

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Pulumi preview
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: dev
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
concurrency:
  group: preview-${{ github.event.number }}
  cancel-in-progress: true
