name: pulumi-up

on:
  workflow_dispatch:
    inputs:
      stack:
        description: Pulumi stack name
        required: true
        default: dev
  push:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/ci.yml
    with:
      run_build: true
      run_lint: false

  up:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Download lambda artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-zip
          path: dist

      - name: Setup Go (for Pulumi program)
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true
          cache-dependency-path: infra/go.sum

      - name: Build Pulumi binary
        working-directory: infra
        run: |
          go mod tidy
          go build -o infra

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Pulumi Up
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: ${{ github.event.inputs.stack }}
          upsert: true
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
