name: pulumi-preview

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/ci.yml
    with:
      run_build: true
      run_lint: false

  preview:
    name: Pulumi preview
    runs-on: ubuntu-latest
    needs: build
    environment: pr
    defaults:
      run:
        working-directory: infra
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Download lambda artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-zip
          path: dist

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Build Pulumi binary
        run: |
          go mod tidy
          go build -o infra

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Pulumi preview
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
