name: test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Go Tests (${{ matrix.module }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - email_ingest
          - loseit_transform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true
          cache-dependency-path: |
            **/go.sum

      - name: Download dependencies
        working-directory: lambda/${{ matrix.module }}
        run: go mod download

      - name: Run tests with coverage
        working-directory: lambda/${{ matrix.module }}
        run: |
          go test -v -race -coverprofile=coverage.out ./...
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.module }}-${{ github.sha }}
          path: lambda/${{ matrix.module }}/coverage.*
